# Generated by Django 5.1.1 on 2024-09-17 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_speakerapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('selected_course', models.CharField(choices=[('leadership', 'Leadership and Management'), ('personal', 'Personal Development'), ('marketing', 'Marketing and Sales'), ('hr', 'Human Resources'), ('organizational', 'Organizational Essentials'), ('administrative', 'Administrative Skills'), ('professional', 'Professional Advancement'), ('career', 'Advanced Career Building')], max_length=20)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
