# Generated by Django 5.1.1 on 2024-09-17 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_courseregistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseFinder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('career_stage', models.CharField(choices=[('Early Career', 'Early Career'), ('Mid-Level', 'Mid-Level'), ('Senior Executive', 'Senior Executive'), ('Career Transition', 'Career Transition')], max_length=50)),
                ('interests', models.JSONField()),
                ('time_commitment', models.CharField(choices=[('1-3 months', '1-3 months'), ('3-6 months', '3-6 months'), ('6-12 months', '6-12 months'), ('1+ year', '1+ year')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
